In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, date
df = pd.read_excel('/Users/surjitdas/Box Sync/Barclays Data Tower/Governance/Operations/Resource Master - IIT.xlsx','Base data')

In [2]:
df.columns

Index(['Contract', 'WP_#', 'Emp_Code', 'First_Name', 'Last_Name',
       'Emp_Notes_ID', 'Band', 'Band_Wt', 'Status', 'Demand_Confidence',
       'Supply_Status', 'Demand_Received', 'Requested_Start_date', 'Billable',
       'NCE_Start_Date', 'NCE_End_Date', 'Transition_Start_Date',
       'Transition_End_Date', 'Billing_Start_Date', 'Billing_End_Date',
       'Billing_Month', 'Billing_Year', 'Billing_End_Month', 'Billing_End_Yr',
       'Unbilled_Days', 'Scoped_vs_Non_Scoped', 'SR_#', 'SR_Start_Date',
       'SR_End_Date', 'BRID', 'BRID_Date', 'Line_Manager', 'IBM POC',
       'Location_Category', 'Skills', 'JRSS', 'Premium', 'PSL_Role',
       'Years_of_Experience', 'Role_Category', 'BCP Critical', 'Comments',
       'Inactive_Reason', 'City'],
      dtype='object')

In [3]:
df.shape

(539, 44)

# Data Quality queries:

In [4]:
#1. Are there duplicate entries for Active?
#2. Are there duplicate entries for Forecast?
df[df.duplicated(['Emp_Notes_ID','Status'], keep=False)]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
446,B04358,T&M,00526Y,Sreenath,Morusu,Sreenath Morusu/India/IBM,6B,6.5,Inactive,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,Moving Projects,Hyderabad
447,B04358,WP2017_004,00526Y,Sreenath,Morusu,Sreenath Morusu/India/IBM,6B,6.5,Inactive,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,Position closed,Hyderabad
470,B04358,WP2017_012,02833V,Supriya,Kale,Supriya B Kale/India/IBM,7A,7.0,Inactive,NaN,...,Java,Application Developer-Java.core,Standard,NaN,4-6,Core dev,NaN,NaN,Moving projects,Pune
471,B04358,WP2017_016,02833V,Supriya,Kale,Supriya B Kale/India/IBM,7A,7.0,Inactive,NaN,...,Java,Application Developer-Java.core,Standard,NaN,4-6,Core dev,NaN,NaN,Work Package completed,Pune

In [5]:
#3. How many (and which) Active Emp Notes ID do not have /IBM (proper notes id)
df[(~df['Emp_Notes_ID'].str.endswith("IBM")) & (df['Status'] == 'Active')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
118,B04358,T&M,NaN,Jakir,Hussain,Jakir Hussain,6B,6.5,Active,NaN,...,Change & Release Management,Change & Release Management,NaN,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
175,B04358,T&M,NaN,Bhupen,Hande,Bhupen Hande,9,9.0,Active,NaN,...,BA,Business Analyst-Technical Requirements,Standard,NaN,6-8,Design,NaN,NaN,NaN,1CP
258,B04358,WP2017_029,NaN,Navneet,Nishant,Navneet Nishant,6B,6.5,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
393,B04358,T&M,0504F6,Sandhya,Namdeo,Sandhya Namdeo,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,2-4,Core Dev,NaN,Consolidation,NaN,Pune
462,B04358,WP2017_029,NaN,Sujatha,REDDY,Sujatha Reddy,6B,6.5,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Pune

In [6]:
#4. How many (and which) Active Emp Codes are missing?
df[(df['Emp_Code'].isnull()) & (df['Status'] == 'Active')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
118,B04358,T&M,NaN,Jakir,Hussain,Jakir Hussain,6B,6.5,Active,NaN,...,Change & Release Management,Change & Release Management,NaN,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
175,B04358,T&M,NaN,Bhupen,Hande,Bhupen Hande,9,9.0,Active,NaN,...,BA,Business Analyst-Technical Requirements,Standard,NaN,6-8,Design,NaN,NaN,NaN,1CP
258,B04358,WP2017_029,NaN,Navneet,Nishant,Navneet Nishant,6B,6.5,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
372,B04358,T&M,NaN,Rina,Kagdelwar,Rina Kagdelwar/India/IBM,6B,6.5,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Development,NaN,NaN,NaN,Pune
462,B04358,WP2017_029,NaN,Sujatha,REDDY,Sujatha Reddy,6B,6.5,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Pune

In [7]:
#5. How many (and which) Bands are missing?
df[(df['Band'].isnull())]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
50,B04358,WP2017_028,AVLXW0,Anil,Gorisipati,Anil Gorisipati04/India/Contr/IBM,NaN,NaN,Active,NaN,...,BI Reporting - Cognos,Application Developer-COGNOS.BI,Standard,NaN,6-8,Core Dev,NaN,Consolidation,NaN,Pune
95,B04358,T&M,NaN,NaN,NaN,Backfill - Avinash Singh10/India/IBM,NaN,NaN,Forecast,Backfill,...,Teradata,Application Developer-Teradata,Premium,NaN,6-8,Core Dev,NaN,NaN,NaN,Bangalore
219,B04358,WP2017_028,NaN,NaN,NaN,Hub Support L3 Resource,NaN,NaN,Forecast,Medium,...,BI Reporting - Qlikview,Application Developer-BI Reporting Tools,Standard,NaN,6-8,Core Dev,NaN,Consolidation,NaN,Bangalore
443,B04358,T&M,02699H,Soumen,Ghosh,Soumen Ghosh5/India/IBM,NaN,NaN,Active,NaN,...,BA,Business Analyst-Technical Requirements,Standard,Business Analyst,6-8,Design,NaN,NaN,NaN,1CP

In [8]:
#6. How many (and which) Line Managers are missing?
df[(df['Line_Manager'].isnull())]

Empty DataFrame
Columns: [Contract, WP_#, Emp_Code, First_Name, Last_Name, Emp_Notes_ID, Band, Band_Wt, Status, Demand_Confidence, Supply_Status, Demand_Received, Requested_Start_date, Billable, NCE_Start_Date, NCE_End_Date, Transition_Start_Date, Transition_End_Date, Billing_Start_Date, Billing_End_Date, Billing_Month, Billing_Year, Billing_End_Month, Billing_End_Yr, Unbilled_Days, Scoped_vs_Non_Scoped, SR_#, SR_Start_Date, SR_End_Date, BRID, BRID_Date, Line_Manager, IBM POC, Location_Category, Skills, JRSS, Premium, PSL_Role, Years_of_Experience, Role_Category, BCP Critical, Comments, Inactive_Reason, City]
Index: []

[0 rows x 44 columns]

In [9]:
#7. How many (and which) JRSS are missing?
df[(df['JRSS'].isnull())]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
306,B04358,T&M,NaN,NaN,NaN,Manish Reporting Resource,6A,6.25,Forecast,Medium,...,NaN,NaN,NaN,NaN,0-2,Development,NaN,Consolidation,NaN,Pune
307,B04358,T&M,NaN,NaN,NaN,Manish SSIS 1,6B,6.50,Forecast,Medium,...,NaN,NaN,NaN,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
308,B04358,T&M,NaN,NaN,NaN,Manish SSIS 2,7A,7.00,Forecast,Medium,...,NaN,NaN,NaN,NaN,6-8,Core Dev,NaN,Consolidation,NaN,Pune
408,B04358,T&M,117348,Shardendu,Chaudhary,Shardendu K Chaudhary/India/IBM,8,8.00,Active,NaN,...,Project Manager,NaN,NaN,NaN,NaN,design,NaN,NaN,NaN,Pune
529,B04358,T&M,NaN,NaN,NaN,UKR Data Analyst,7A,7.00,Forecast,Medium,...,NaN,NaN,NaN,NaN,6-8,Design,NaN,NaN,NaN,Pune
530,B04358,T&M,NaN,NaN,NaN,UCL Designer,7B,7.50,Forecast,Medium,...,NaN,NaN,NaN,NaN,10-12,Design,NaN,NaN,NaN,Pune

In [10]:
#8. How many (and which) Active Years of Experience are missing?
df[(df['Years_of_Experience'].isnull()) & (df['Status'] == 'Active')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
224,B04358,WP2017_016,0313B3,Kunal,Patil,Kunal D Patil/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,NaN,Development,NaN,NaN,NaN,Bangalore
286,B04358,WP2017_016,05429R,Prachi,Moharana,Prachi P Moharana/India/IBM,6A,6.25,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,NaN,Development,NaN,NaN,NaN,Bangalore
408,B04358,T&M,117348,Shardendu,Chaudhary,Shardendu K Chaudhary/India/IBM,8,8.00,Active,NaN,...,Project Manager,NaN,NaN,NaN,NaN,design,NaN,NaN,NaN,Pune
420,B04358,WP2017_004,0429B7,Shweta,Verma,Shweta Verma1/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,Developer,NaN,Development,NaN,NaN,NaN,Pune
531,B04363,Lineage,02509Z,Dileep,Dominic,Dileep R Dominic/India/IBM,7A,7.00,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,NaN,Core Dev,NaN,NaN,NaN,Pune

In [11]:
#9. How many (and which) Active PSL Role are missing?
df[(df['PSL_Role'].isnull()) & (df['Status'] == 'Active')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
19,B04358,T&M,04292O,Abhishek,Kamavisdhar,Abhishek M Kamavisdar/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,2-4,Core Dev,NaN,Consolidation,NaN,Pune
20,B04358,T&M,06860A,Abhishek,Swami,Abhishek Swami1/India/IBM,7A,7.00,Active,NaN,...,Cobol,Application Developer-COBOL,Standard,NaN,10-12,Core Dev,NaN,NaN,NaN,Pune
21,B04358,WP2017_004,04192Z,Abinash,Parida,Abinash Parida/India/IBM,7A,7.00,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.AB INITIO,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Banglore
22,B04358,WP2017_023,04293Q,Abir,Ganguly,Abir Ganguly/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,2-4,Core Dev,NaN,NaN,NaN,Pune
23,B04358,T&M,02126Y,Aditya,Shah,Aditya Shah334/India/IBM,7A,7.00,Active,NaN,...,Change & Release Management,Change & Release Management,NaN,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
25,B04358,WP2017_017,00072I,Aishwarya,Das,Aishwarya Das/India/IBM,7A,7.00,Active,NaN,...,Big Data - Spark,Application Developer-Big Data BigInsights,Premium,NaN,6-8,Design,NaN,NaN,NaN,UK
37,B04363,Lineage,03506T,Ajay,Chougule,Ajay B Chougule/India/IBM,6B,6.50,Active,NaN,...,Cobol,Application Developer-COBOL,Standard,NaN,2-4,Development,NaN,NaN,NaN,Pune
39,B04363,Lineage,03465V,Akash,Birari,Akash Birari/India/IBM,7B,7.50,Active,NaN,...,SAS,Data Specialist-Data Governance,Premium,NaN,10-12,Design,NaN,NaN,NaN,Pune
40,B04363,NaN,0417C5,Amit,Srivastava,Amit K Srivastava012/India/IBM,6G,6.00,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,0-2,Development,NaN,NaN,NaN,Pune
43,B04363,Lineage,03014N,Amit,Pandey,Amit Pandey24/India/IBM,6A,6.25,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,2-4,Development,NaN,NaN,NaN,Bangalore
44,B04358,WP2017_023,00770A,Amita,Gada,Amita S Gada/India/IBM,6B,6.50,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,2-4,Core Dev,NaN,NaN,NaN,Pune
45,B04358,T&M,05927G,Amol,Patil,Amol Patil/India/IBM,7A,7.00,Active,NaN,...,Program Manager,Technical Team Leader-Middleware,Standard,NaN,8-10,Design,NaN,NaN,NaN,Pune
48,B04363,Lineage,0294E3,Amrita,Chrispin,Amrita J Chrispin/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Bangalore
49,B04363,Lineage,04932X,Amrutha,Srivatsaya,Amrutha Srivatsavaya/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,0-2,Development,NaN,NaN,NaN,Pune
50,B04358,WP2017_028,AVLXW0,Anil,Gorisipati,Anil Gorisipati04/India/Contr/IBM,NaN,NaN,Active,NaN,...,BI Reporting - Cognos,Application Developer-COGNOS.BI,Standard,NaN,6-8,Core Dev,NaN,Consolidation,NaN,Pune
51,B04363,Lineage,03599Y,Anil,Bhaskara,Anil K Bhaskara/India/IBM,7A,7.00,Active,NaN,...,SAS,Data Specialist-Data Governance,Premium,NaN,6-8,Core Dev,NaN,NaN,NaN,Bangalore
52,B04363,Lineage,AVLV66,Anjali,Garg,Anjali G 66/India/Contr/IBM,7A,7.00,Active,NaN,...,.NET,Application Developer-C#.NET,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
53,B04358,T&M,08416G,Ankit,Bhadauria,Ankit Bhadauria1/India/IBM,7A,7.00,Active,NaN,...,ETL Testing,Application Developer-Big Data Tools,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Pune
55,B04358,WP2017_030,464554,Ankit,Patel,Ankit D Patel/India/IBM,7B,7.50,Active,NaN,...,ETL Testing,Project Manager-Business Analytics & Strategy,Premium,NaN,>12,Core Dev,NaN,NaN,NaN,Pune
57,B04363,Lineage,061896,Anshul,Gupta,Anshul Gupta3/India/IBM,08,8.00,Active,NaN,...,Program Manager,Project Manager-Custom Development,Standard,NaN,>12,Design,NaN,NaN,NaN,Pune
60,B04363,Lineage,06065D,Anup,Gavate,Anup L Gavate/India/IBM,7A,7.00,Active,NaN,...,.NET,Application Developer-C#.NET,Standard,NaN,2-4,Development,NaN,NaN,NaN,Pune
63,B04363,Lineage,01919Q,Anurag,Jain,Anurag Jain025/India/IBM,7B,7.50,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,>12,Design,NaN,NaN,NaN,Pune
64,B04363,Lineage,09702C,Anuya,Singhai,Anuya Singhai/India/IBM,7A,7.00,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,8-10,Design,NaN,NaN,NaN,Bangalore
85,B04358,WP2017_017,066038,Arun,Ramasamy,Arun Ramasamy/India/IBM,08,8.00,Active,NaN,...,Architect,Application Architect-Web Technologies,Standard,NaN,>12,Design,NaN,NaN,NaN,Pune
88,B04363,Lineage,04095W,Ashish,Singh,Ashish K Singh96/India/IBM,6G,6.00,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,0-2,Development,NaN,NaN,NaN,Pune
92,B04363,Lineage,09355E,Ashwini,Mukare,Ashwini A Mukare/India/IBM,6A,6.25,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,0-2,Development,NaN,NaN,NaN,Pune
93,B04363,Lineage,874359,Atul,Yadav,Atul Yadav/India/IBM,7B,7.50,Active,NaN,...,Mainframe,Technical Team Leader-Mainframe,Standard,NaN,10-12,Design,NaN,NaN,NaN,Pune
94,B04358,T&M,02345P,Avinash,Singh,Avinash Singh10/India/IBM,6B,6.50,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,6-8,Core Dev,NaN,NaN,NaN,Bangalore
105,B04358,T&M,0504H6,Bhargav,Mandapara,Bhargavkumar K Mendapara/India/IBM,6B,6.50,Active,NaN,...,Change & Release Management,Change & Release Management,NaN,NaN,2-4,Core Dev,NaN,Consolidation,NaN,Pune
112,B04358,WP2017_028,00930N,Biswamitra,Paul,Biswamitra Paul/India/IBM,6B,6.50,Active,NaN,...,BI Reporting - Cognos,Application Developer-COGNOS.BI,Standard,NaN,4-6,Development,NaN,Consolidation,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,B04358,WP2017_017,03792W,Srikanth,Merugu,Srikanth Merugu3/India/IBM,6B,6.50,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,2-4,Development,NaN,NaN,NaN,Pune
453,B04358,WP2017_030,AVHWSK,Pandilla,Srikant,Srikanth Reddy Pandilla21/India/Contr/IBM,6B,6.50,Active,NaN,...,Java,Application Developer-Java.Core,Standard,NaN,2-4,Development,NaN,NaN,NaN,Pune
456,B04363,Lineage,05320F,Subhamoy,Guha,Subhamoy K Guha/India/IBM,9,9.00,Active,NaN,...,Architect,Application Architect-Business Intelligence,Premium,NaN,>12,Design,NaN,NaN,NaN,Pune
457,B04358,WP2017_004,357133,Subhashini,Rangaswamy,Subhashini Rangaswamy/India/IBM,7A,7.00,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Development,NaN,NaN,NaN,Bangalore
460,B04358,T&M,0504G4,Sudipta,Roy,Sudipta Roy901/India/IBM,7A,7.00,Active,NaN,...,ETL Informatica,Data Specialist-ETL.Informatica,Premium,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
462,B04358,WP2017_029,NaN,Sujatha,REDDY,Sujatha Reddy,6B,6.50,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Pune
467,B04363,WP2017_002,00566Z,Sunil,Dangayach,Sunil Dangayach/India/IBM,7A,7.00,Active,NaN,...,Java,Application Developer-Cloud.Java,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
468,B04358,T&M,AVLFJG,Sunil,Hasannapuram,Sunil Hasannapuram/India/Contr/IBM,6B,6.50,Active,NaN,...,ETL Testing,TEST SPECIALIST-TEST DATA MANAGEMENT,Standard,NaN,2-4,Development,NaN,NaN,NaN,Hyderabad
472,B04358,WP2017_028,0295A4,Surendra Reddy,Etukala,Surendra R Etukala/India/IBM,6B,6.50,Active,NaN,...,BI Reporting - Actuate,Application Developer-BI Reporting Tools,Standard,NaN,6-8,Core Dev,NaN,Consolidation,NaN,Bangalore
473,B04358,T&M,074687,Suresh,Borra,Suresh B Borra1/India/IBM,6B,6.50,Active,NaN,...,Change & Release Management,Change & Release Management,NaN,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
475,B04358,T&M,0491J9,Swapnil,Gawai,Swapnil D Gawai/India/IBM,6B,6.50,Active,NaN,...,ETL Informatica,Data Specialist-ETL.Informatica,Premium,NaN,2-4,Core Dev,NaN,Consolidation,NaN,Pune
476,B04358,WP2017_030,0414G8,Swapnil,Kamdar,Swapnil Kamdar/India/IBM,6B,6.50,Active,NaN,...,Java,Application Developer-Java.Spring,Standard,NaN,4-6,Development,NaN,NaN,NaN,Pune
479,B04358,T&M,05032X,Tapas,Sahoo,Tapas R Sahoo/India/IBM,7A,7.00,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Pune
481,B04358,WP2017_030,0427D4,Vijay,Pandit,Vijay Pandit/India/IBM,7A,7.00,Active,NaN,...,Java,Application Developer-Java.Spring,Standard,NaN,6-8,NaN,NaN,NaN,NaN,Pune
482,B04358,WP2017_030,0314C7,Shraddha,Chandra,Shraddha Chandra/India/IBM,6B,6.50,Active,NaN,...,Java,Application Developer-Java.Spring,Standard,NaN,6-8,NaN,NaN,NaN,NaN,Pune
498,B04358,WP2017_030,0129F9,Udit,Asati,Udit Asati011/India/IBM,7A,7.00,Active,NaN,...,Java,Business Analyst-Technical Requirements,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
500,B04358,T&M,0505G9,Udita,Pathak,Udita Pathak/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,2-4,Development,NaN,NaN,NaN,Pune
501,B04358,WP2017_028,084145,Ujjaval K,Chowdhari,Ujjaval K Choudhri/India/IBM,7A,7.00,Active,NaN,...,BI Reporting - Cognos,Application Developer-COGNOS.BI,Standard,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Pune
504,B04363,Lineage,04933U,Upayan,Nayak,Upayan Nayak/India/IBM,7B,7.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,0-2,Core Dev,NaN,NaN,NaN,Pune
505,B04358,T&M,04193V,Vaishali,Papneja,Vaishali 1213/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
507,B04358,T&M,07550A,Vasanth,Ladda,Vasanth Ladda/India/IBM,7A,7.00,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,10-12,Core Dev,NaN,NaN,NaN,Hyderabad
509,B04358,T&M,AVLKLB,Venkata,Setty,Venkatanarasaiah Setti/India/Contr/IBM,6B,6.50,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,4-6,Development,NaN,NaN,NaN,Pune
513,B04358,WP2017_017,0360A2,Vikram,Suthar,Vikram Suthar/India/IBM,7A,7.00,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,4-6,Development,NaN,NaN,NaN,Pune
515,B04358,WP2017_017,021960,Vikram,Bhosle,Vikram V Bhosle/India/IBM,08,8.00,Active,NaN,...,Business Analyst,Business Analyst-Rational,Standard,NaN,>12,Design,NaN,NaN,NaN,Pune
516,B04358,WP2017_004,04046X,Vinay,Ravikumar,Vinay K Ravikumar/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,2-4,Development,NaN,NaN,NaN,Bangalore
520,B04358,T&M,05146Y,Vishal,Chadokar,Vishal Chadokar08/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Pune
522,B04363,Lineage,03381Y,Vishal,Patil,Vishal Patil5/India/IBM,6B,6.50,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,NaN,2-4,Development,NaN,NaN,NaN,Pune
523,B04363,Lineage,09216I,Vishal,Singh,Vishal Singh33/India/IBM,6A,6.25,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,0-2,Development,NaN,NaN,NaN,Pune
528,B04358,T&M,01144U,ZISHAN,SYED,Zishan Syed/India/IBM,7B,7.50,Active,NaN,...,Teradata,Project Manager-Complex Programs.BAS,Standard,NaN,6-8,Development,NaN,NaN,NaN,Pune
531,B04363,Lineage,02509Z,Dileep,Dominic,Dileep R Dominic/India/IBM,7A,7.00,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,NaN,Core Dev,NaN,NaN,NaN,Pune

In [12]:
#10. How many (and which) Active Role Category are missing?
df[(df['Role_Category'].isnull()) & (df['Status'] == 'Active')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
268,B04358,WP2017_030,0479O8,nishigandha,Omanwar,Nishigandha Omanwar/India/IBM,7B,7.5,Active,NaN,...,Java,Application Architect-Java,Standard,NaN,6-8,NaN,NaN,NaN,NaN,Pune
415,B04358,WP2017_030,09141I,Shrikant,Khupat,Shrikant L Khupat1/India/IBM,08,8.0,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,6-8,NaN,NaN,NaN,NaN,Pune
481,B04358,WP2017_030,0427D4,Vijay,Pandit,Vijay Pandit/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Java.Spring,Standard,NaN,6-8,NaN,NaN,NaN,NaN,Pune
482,B04358,WP2017_030,0314C7,Shraddha,Chandra,Shraddha Chandra/India/IBM,6B,6.5,Active,NaN,...,Java,Application Developer-Java.Spring,Standard,NaN,6-8,NaN,NaN,NaN,NaN,Pune

In [13]:
#11. How many (and which) Active City are missing?
df[(df['City'].isnull()) & (df['Status'] == 'Active')]

Empty DataFrame
Columns: [Contract, WP_#, Emp_Code, First_Name, Last_Name, Emp_Notes_ID, Band, Band_Wt, Status, Demand_Confidence, Supply_Status, Demand_Received, Requested_Start_date, Billable, NCE_Start_Date, NCE_End_Date, Transition_Start_Date, Transition_End_Date, Billing_Start_Date, Billing_End_Date, Billing_Month, Billing_Year, Billing_End_Month, Billing_End_Yr, Unbilled_Days, Scoped_vs_Non_Scoped, SR_#, SR_Start_Date, SR_End_Date, BRID, BRID_Date, Line_Manager, IBM POC, Location_Category, Skills, JRSS, Premium, PSL_Role, Years_of_Experience, Role_Category, BCP Critical, Comments, Inactive_Reason, City]
Index: []

[0 rows x 44 columns]

In [14]:
#12. Which Inactive records have Inactive_Reason missing?
df[(df['Status'] == 'Inactive') & df.Inactive_Reason.isnull()]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
184,B04321,Multi Bureau,AVLHDP,Gopikrishna,Velanati,Gopi Krishna Velanati21/India/Contr/IBM,6B,6.5,Inactive,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,2-4,Development,NaN,LWD in IBM 28th June 2017,NaN,Hyderabad
208,B04363,WP2017_002,0125B1,Kajal,Sanghi,Kajal Sanghi/India/IBM,7A,7.0,Inactive,NaN,...,Java,Application Developer-Java.Spring,Standard,NaN,10-12,Design,NaN,NaN,NaN,Pune

# Data Updation issues:

In [15]:
from datetime import datetime,timedelta
now = datetime.now()

#1. Which Active resources have Billing End Date in the next 30 days?
df[(~df['Billing_End_Date'].isnull()) & (df['Billing_End_Date'] < now + timedelta(days=30))& (df['Status'] == 'Active')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
62,B04358,T&M,0240G7,Anuradha,Patil,Anuradha D Patil/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,2-4,Core Dev,NaN,NaN,NaN,Bangalore
97,B04358,T&M,0110B7,Ayon,Hazra,Ayon Hazra011/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,NaN,Pune
150,B04363,WP2017_014,0319A9,Diptiman,Yarte,Diptiman B Yarte/India/IBM,7A,7.00,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,4-6,Development,NaN,NaN,NaN,Pune
152,B04358,T&M,03658R,EKAMPREET,AHUJA,Ekampreet Kaur/India/IBM,7B,7.50,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,8-10,Design,NaN,NaN,NaN,Pune
174,B04363,WP2017_015,02671T,Gaurav,Neekhra,Gaurav Neekhra02/India/IBM,7A,7.00,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
218,B04358,WP2017_016,0432C8,Kiran,B,Kiran B13/India/IBM,7A,7.00,Active,NaN,...,BI Reporting - Qlikview,Application Developer-BI Reporting Tools,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Bangalore
220,B04358,T&M,09211B,Kishore,Gudipati,Kishore Gudipati/India/IBM,08,8.00,Active,NaN,...,Business Analyst,Business Analyst-Business Intelligence,Premium,Sr. Business Analyst,>12,Design,NaN,NaN,NaN,Hyderabad
224,B04358,WP2017_016,0313B3,Kunal,Patil,Kunal D Patil/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,NaN,Development,NaN,NaN,NaN,Bangalore
246,B04358,T&M,0093F9,Milind,Ganure,Milind Ganure/India/IBM,7A,7.00,Active,NaN,...,ETL Ab Initio,Application Architect-Business Intelligence,Premium,NaN,6-8,Core Dev,NaN,Will be replaced in the next couple of weeks b...,NaN,Pune
286,B04358,WP2017_016,05429R,Prachi,Moharana,Prachi P Moharana/India/IBM,6A,6.25,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,NaN,Development,NaN,NaN,NaN,Bangalore
303,B04358,T&M,0028D5,PRIYANKA,ROY,Priyanka Roy6/India/IBM,7B,7.50,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,Architect,10-12,Design,NaN,NaN,NaN,Pune
320,B04363,WP2017_002,0131C2,Rashmi,Padale,Rashmi S Padale/India/IBM,7A,7.00,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,8-10,Core Dev,NaN,NaN,NaN,Pune
325,B04363,WP2017_014,05418B,Ravindra,Baviskar,Ravindra G Baviskar/India/IBM,7B,7.50,Active,NaN,...,Java,Application Architect-Cloud.Custom Development,Standard,NaN,8-10,Design,NaN,NaN,NaN,Pune
392,B04358,T&M,539027,Sandeep,Kumar,Sandeep Kumar5/India/IBM,7A,7.00,Active,NaN,...,Project Manager,Data Management Support Specialist-ETL.Informa...,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
393,B04358,T&M,0504F6,Sandhya,Namdeo,Sandhya Namdeo,7A,7.00,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,2-4,Core Dev,NaN,Consolidation,NaN,Pune
395,B04321,Multi Bureau,02809V,Santosh,Nalamas,Santosh K Nalmas/India/IBM,6A,6.25,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,2-4,Development,NaN,No BRID & Left IBM on 24th May 2017,Attrition,Hyderabad
454,B04363,NaN,25171,Srinivasa,Vomaravilli,Srinivasa R Vomaravilli/India/IBM,7A,7.00,Active,NaN,...,ETL Testing,Test Specialist-Test Consulting,Standard,Architect,8-10,Core Dev,NaN,Assigned on MultiBureau till 7th July with buf...,NaN,Hyderabad
455,B04358,WP2017_004,01060R,Srinivasarao,Uttaravilli,Srinivasarao Uttaravilli/India/IBM,6B,6.50,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,Developer,4-6,Development,NaN,NaN,NaN,Hyderabad
467,B04363,WP2017_002,00566Z,Sunil,Dangayach,Sunil Dangayach/India/IBM,7A,7.00,Active,NaN,...,Java,Application Developer-Cloud.Java,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
511,B04363,WP2017_015,01813X,VIJAYKUMAR,WADIKAR,Vijaykumar B Wadikar/India/IBM,7A,7.00,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune

In [16]:
#2. Which Active resourcesâ€™ Billing End Date is in the past?
df[(~df['Billing_End_Date'].isnull()) & (df['Billing_End_Date'] < now)& (df['Status'] == 'Active')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
97,B04358,T&M,0110B7,Ayon,Hazra,Ayon Hazra011/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,NaN,Pune
218,B04358,WP2017_016,0432C8,Kiran,B,Kiran B13/India/IBM,7A,7.00,Active,NaN,...,BI Reporting - Qlikview,Application Developer-BI Reporting Tools,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Bangalore
220,B04358,T&M,09211B,Kishore,Gudipati,Kishore Gudipati/India/IBM,08,8.00,Active,NaN,...,Business Analyst,Business Analyst-Business Intelligence,Premium,Sr. Business Analyst,>12,Design,NaN,NaN,NaN,Hyderabad
224,B04358,WP2017_016,0313B3,Kunal,Patil,Kunal D Patil/India/IBM,6B,6.50,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,NaN,Development,NaN,NaN,NaN,Bangalore
246,B04358,T&M,0093F9,Milind,Ganure,Milind Ganure/India/IBM,7A,7.00,Active,NaN,...,ETL Ab Initio,Application Architect-Business Intelligence,Premium,NaN,6-8,Core Dev,NaN,Will be replaced in the next couple of weeks b...,NaN,Pune
286,B04358,WP2017_016,05429R,Prachi,Moharana,Prachi P Moharana/India/IBM,6A,6.25,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,NaN,Development,NaN,NaN,NaN,Bangalore
303,B04358,T&M,0028D5,PRIYANKA,ROY,Priyanka Roy6/India/IBM,7B,7.50,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,Architect,10-12,Design,NaN,NaN,NaN,Pune
320,B04363,WP2017_002,0131C2,Rashmi,Padale,Rashmi S Padale/India/IBM,7A,7.00,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,8-10,Core Dev,NaN,NaN,NaN,Pune
395,B04321,Multi Bureau,02809V,Santosh,Nalamas,Santosh K Nalmas/India/IBM,6A,6.25,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,2-4,Development,NaN,No BRID & Left IBM on 24th May 2017,Attrition,Hyderabad
454,B04363,NaN,25171,Srinivasa,Vomaravilli,Srinivasa R Vomaravilli/India/IBM,7A,7.00,Active,NaN,...,ETL Testing,Test Specialist-Test Consulting,Standard,Architect,8-10,Core Dev,NaN,Assigned on MultiBureau till 7th July with buf...,NaN,Hyderabad
455,B04358,WP2017_004,01060R,Srinivasarao,Uttaravilli,Srinivasarao Uttaravilli/India/IBM,6B,6.50,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,Developer,4-6,Development,NaN,NaN,NaN,Hyderabad
467,B04363,WP2017_002,00566Z,Sunil,Dangayach,Sunil Dangayach/India/IBM,7A,7.00,Active,NaN,...,Java,Application Developer-Cloud.Java,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
511,B04363,WP2017_015,01813X,VIJAYKUMAR,WADIKAR,Vijaykumar B Wadikar/India/IBM,7A,7.00,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune

In [17]:
#3. Which Forecast resourcesâ€™ NCE Start Date is in the past?
df[(~df['NCE_Start_Date'].isnull()) & (df['NCE_Start_Date'] < now)& (df['Status'] == 'Forecast')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
66,B04358,T&M,NaN,NaN,NaN,Neelu Rai,6B,6.50,Forecast,Medium,...,BI Reporting - Cognos,Application Developer-COGNOS.BI,Standard,NaN,4-6,Development,NaN,Consolidation,NaN,Pune
96,B04358,T&M,NaN,NaN,NaN,Ayon backfill - Ab Initio - Yogita Nehe,7B,7.50,Forecast,Backfill,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
197,B04358,T&M,NaN,NaN,NaN,Santosh Kumar,7B,7.50,Forecast,High,...,BA,Business Analyst-Technical Requirements,Standard,NaN,4-6,Design,NaN,NaN,NaN,Pune
272,B04358,WP2017_029,NaN,NaN,NaN,ODS Testing 3,6A,6.25,Forecast,High,...,ETL Testing,Test Specialist-Data,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
386,B04358,T&M,NaN,Sai Satish Chandra,Kiran,Sai Kiran,7A,7.00,Forecast,Medium,...,BI Reporting - Qlikview,Application Developer-BI Reporting Tools,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
403,B04358,T&M,NaN,NaN,NaN,SBI Testing 1 - Srinivas V,7A,7.00,Forecast,Medium,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Development,NaN,Consolidation,NaN,Pune
404,B04358,T&M,NaN,NaN,NaN,SBI Testing 2 - Jahnavi K,6A,6.25,Forecast,Medium,...,ETL Testing,Test Specialist-Data,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
410,B04358,T&M,05217X,Sikha,Batra,Shikha Batra1/India/IBM,7B,7.50,Forecast,High,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,2-4,Core Dev,NaN,NaN,NaN,Bangalore
424,B04358,T&M,03487N,Siva M,Ganesh,Siva M Ganesh/India/IBM,7A,7.00,Forecast,Medium,...,BI Reporting - Cognos,Application Developer-COGNOS.BI,Standard,NaN,8-10,Design,NaN,Consolidation,NaN,Pune
445,B04358,T&M,08846E,Sree Divya,Tulimilli,Sree Tulimilli/India/IBM,6A,6.25,Forecast,Medium,...,BI Reporting - Cognos,Application Developer-COGNOS.BI,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
537,B04358,T&M,0438B2,Chandan,Nandy,Chandan Nandy2/India/IBM,08,8.00,Forecast,High,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,Architect,10-12,Design,NaN,NaN,NaN,Pune

In [18]:
#4. Which Forecast resourcesâ€™ Transition Start Date is in the past?
df[(~df['Transition_Start_Date'].isnull()) & (df['Transition_Start_Date'] < now)& (df['Status'] == 'Forecast')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
157,B04358,T&M,NaN,NaN,NaN,ETL Testing - Ab Initio/Infa 4,6A,6.25,Forecast,Low,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Development,NaN,Consolidation,NaN,Pune
158,B04358,T&M,NaN,NaN,NaN,ETL Testing - Ab Initio/Infa 5,7A,7.00,Forecast,Low,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Development,NaN,Consolidation,NaN,Pune
159,B04358,T&M,NaN,NaN,NaN,ETL Testing - Ab Initio/Infa 6,7B,7.50,Forecast,Low,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Development,NaN,Consolidation,NaN,Pune
272,B04358,WP2017_029,NaN,NaN,NaN,ODS Testing 3,6A,6.25,Forecast,High,...,ETL Testing,Test Specialist-Data,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
484,B04358,T&M,NaN,NaN,NaN,TBD Informatica 1,6B,6.50,Forecast,High,...,ETL Informatica,Data Management Support Specialist-ETL.Informa...,Premium,Senior Developer,6-8,Core Dev,NaN,Consolidation,NaN,Pune

In [19]:
#5. Which Forecast resourcesâ€™ Billing Start Date is in the past?
df[(~df['Billing_Start_Date'].isnull()) & (df['Billing_Start_Date'] < now)& (df['Status'] == 'Forecast')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
99,B04358,T&M,NaN,NaN,NaN,Backfill - Priyanka Roy6/India/IBM - Mahesh Bo...,7B,7.5,Forecast,Backfill,...,Teradata,Application Developer-Teradata,Premium,Architect,10-12,Design,NaN,NaN,NaN,Pune
201,B04358,T&M,NaN,NaN,NaN,Java / Appzillon TBD,7A,7.0,Forecast,Low,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Pune
249,B04358,T&M,NaN,NaN,NaN,Mongo DB 1,7A,7.0,Forecast,Low,...,Big Data - MongoDB,Application Developer-Big Data Tools,Premium,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Pune
250,B04358,T&M,NaN,NaN,NaN,Mongo DB 2,7A,7.0,Forecast,Low,...,Big Data - MongoDB,Application Developer-Big Data Tools,Premium,NaN,6-8,Design,NaN,Consolidation,NaN,Pune
257,B04358,T&M,NaN,Yelluru Naveen\nYelluru Naveen,Kumar,Naveen Kumar,6B,6.5,Forecast,High,...,Teradata,Application Developer-Teradata,Premium,NaN,2-4,Development,NaN,NaN,NaN,Bangalore
278,B04358,T&M,NaN,NaN,NaN,Pawan - Ab Initio 1 - Sakshi Saxena,6B,6.5,Forecast,High,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,2-4,Core Dev,NaN,NaN,NaN,Pune
279,B04358,T&M,NaN,NaN,NaN,Pawan - Ab Initio 2 - Snehal Thakare,6B,6.5,Forecast,High,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,2-4,Core Dev,NaN,NaN,NaN,Pune
280,B04358,T&M,NaN,NaN,NaN,Pawan - Ab Initio 3,7A,7.0,Forecast,High,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,4-6,Core Dev,NaN,NaN,NaN,Pune
281,B04358,T&M,NaN,NaN,NaN,Pawan - Ab Initio 4,7B,7.5,Forecast,High,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,2-4,Core Dev,NaN,NaN,NaN,Pune
485,B04358,T&M,NaN,NaN,NaN,TBD Mongo DB 1,6B,6.5,Forecast,Medium,...,Big Data - MongoDB,Application Developer-Big Data Tools,Premium,NaN,2-4,Development,NaN,NaN,NaN,Pune
486,B04358,T&M,NaN,NaN,NaN,TBD Mongo DB 2,7A,7.0,Forecast,Medium,...,Big Data - MongoDB,Application Developer-Big Data Tools,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Pune
493,B04358,T&M,NaN,NaN,NaN,Tushar Ab Initio 1 - Thapaswi M,6B,6.5,Forecast,High,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,6-8,Design,NaN,Consolidation,NaN,Pune
502,B04358,T&M,NaN,NaN,NaN,UKR Ab Initio,6B,6.5,Forecast,High,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Pune
536,B04358,T&M,NaN,NaN,NaN,Project Management - WITHDRAWN - PLS DELETE,8,8.0,Forecast,Low,...,Project Manager,Project Manager-Business Analytics & Strategy,Premium,NaN,6-8,Design,NaN,Consolidation,NaN,Pune

In [20]:
#6. Which Inactive resourcesâ€™ Billing End Date is in the future or is missing?
df[((df['Billing_End_Date'].isnull()) | (df['Billing_End_Date'] > now)) & (df['Status'] == 'Inactive')]

Empty DataFrame
Columns: [Contract, WP_#, Emp_Code, First_Name, Last_Name, Emp_Notes_ID, Band, Band_Wt, Status, Demand_Confidence, Supply_Status, Demand_Received, Requested_Start_date, Billable, NCE_Start_Date, NCE_End_Date, Transition_Start_Date, Transition_End_Date, Billing_Start_Date, Billing_End_Date, Billing_Month, Billing_Year, Billing_End_Month, Billing_End_Yr, Unbilled_Days, Scoped_vs_Non_Scoped, SR_#, SR_Start_Date, SR_End_Date, BRID, BRID_Date, Line_Manager, IBM POC, Location_Category, Skills, JRSS, Premium, PSL_Role, Years_of_Experience, Role_Category, BCP Critical, Comments, Inactive_Reason, City]
Index: []

[0 rows x 44 columns]

## Key insights:

In [21]:
#1. List the key Ab Initio Leads (7B & above)
df[(df.Band.isin(['7B',8,9])) & (df['Status'] == 'Active')  & (df['Skills'] == 'ETL Ab Initio')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
63,B04363,Lineage,01919Q,Anurag,Jain,Anurag Jain025/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,>12,Design,NaN,NaN,NaN,Pune
152,B04358,T&M,03658R,EKAMPREET,AHUJA,Ekampreet Kaur/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,8-10,Design,NaN,NaN,NaN,Pune
283,B04358,T&M,0053D2,PIYUSH,JAISWAL,Piyush Jaiswal1/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,8-10,Design,NaN,NaN,NaN,Pune
291,B04358,T&M,03894W,PRASENJIT,PATRA,Prasenjit Patra1/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,Architect,10-12,Design,NaN,NaN,NaN,Pune
388,B04358,T&M,00309W,SAKET,KULKARNI,Saket Kulkarni/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,8-10,Design,NaN,NaN,NaN,Pune
391,B04363,Lineage,04157R,Sam,Julian,Sam J Julian/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,8-10,Design,NaN,NaN,NaN,Bangalore
449,B04358,T&M,09764A,SRIDHAR,SINGH,Sridhar K Singh/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,10-12,Design,NaN,NaN,Moving Projects,Pune
461,B04358,T&M,04754S,Suhas,Kulkarni,Suhas S Kulkarni1/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,2-4,Development,NaN,NaN,NaN,Pune
504,B04363,Lineage,04933U,Upayan,Nayak,Upayan Nayak/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,0-2,Core Dev,NaN,NaN,NaN,Pune
519,B04358,T&M,0061F9,VIPUL,SONI,Vipul Soni/India/IBM,7B,7.5,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,8-10,Design,NaN,NaN,NaN,Pune

In [22]:
#2. List all other leads (7B & above)
df[(df.Band.isin(['7B',8,9])) & (df['Status'] == 'Active')  & (df['Skills'] != 'ETL Ab Initio')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
17,B04358,T&M,06447O,Abhijit,Pendse,Abhijith V Pensdse/India/IBM,8,8.0,Active,NaN,...,Data Modeling,Business Transformation Consultant-BI Strategy,Premium,Architect,>12,Design,NaN,NaN,NaN,Pune
39,B04363,Lineage,03465V,Akash,Birari,Akash Birari/India/IBM,7B,7.5,Active,NaN,...,SAS,Data Specialist-Data Governance,Premium,NaN,10-12,Design,NaN,NaN,NaN,Pune
55,B04358,WP2017_030,464554,Ankit,Patel,Ankit D Patel/India/IBM,7B,7.5,Active,NaN,...,ETL Testing,Project Manager-Business Analytics & Strategy,Premium,NaN,>12,Core Dev,NaN,NaN,NaN,Pune
93,B04363,Lineage,874359,Atul,Yadav,Atul Yadav/India/IBM,7B,7.5,Active,NaN,...,Mainframe,Technical Team Leader-Mainframe,Standard,NaN,10-12,Design,NaN,NaN,NaN,Pune
115,B04358,T&M,0313F4,Chandrani,Singh,Chandrani Singh1/India/IBM,7B,7.5,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,2-4,Development,NaN,NaN,NaN,Bangalore
172,B04358,T&M,07083P,GANESH,TRIPATHI,Ganesh Tripathi/India/IBM,7B,7.5,Active,NaN,...,Architect,Application Architect-Big Data,Premium,Architect,6-8,Design,NaN,NaN,NaN,London
173,B04358,T&M,01375U,GAURAV,CHATURVEDI,Gaurav Chaturvedi3/India/IBM,7B,7.5,Active,NaN,...,ETL Informatica,Data Management Support Specialist-ETL.Informa...,Premium,Architect,10-12,Design,NaN,NaN,NaN,Pune
175,B04358,T&M,NaN,Bhupen,Hande,Bhupen Hande,9,9.0,Active,NaN,...,BA,Business Analyst-Technical Requirements,Standard,NaN,6-8,Design,NaN,NaN,NaN,1CP
204,B04358,T&M,03077C,Joseph Daniel,Kakati,Joseph D Kaka/India/IBM,7B,7.5,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,6-8,Design,NaN,Consolidation,NaN,Hyderabad
211,B04358,T&M,04445K,Karthikeyan,Gurusankaran,Karthikeyan Gurusankaran/India/IBM,7B,7.5,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,6-8,Core Dev,NaN,Consolidation,NaN,Bangalore
233,B04358,T&M,011004,Mai,MA,Mai Tran/Norway/IBM,8,8.0,Active,NaN,...,Architect,Application Architect-Big Data,Premium,NaN,>12,Design,NaN,NaN,NaN,London
264,B04358,T&M,01304R,Nikhil,Shah,Nikhil Shah1/India/IBM,7B,7.5,Active,NaN,...,BA,Business Analyst-Technical Requirements,Standard,Business Analyst,6-8,Design,NaN,NaN,NaN,1CP
268,B04358,WP2017_030,0479O8,nishigandha,Omanwar,Nishigandha Omanwar/India/IBM,7B,7.5,Active,NaN,...,Java,Application Architect-Java,Standard,NaN,6-8,NaN,NaN,NaN,NaN,Pune
271,B04358,WP2017_017,01376H,Nitin,Sharma,Nitin Sharma15/India/IBM,7B,7.5,Active,NaN,...,Big Data - Spark,Application Developer-Big Data BigInsights,Premium,NaN,10-12,Design,NaN,NaN,NaN,Pune
290,B04358,T&M,04119Q,Prasanna,Devaraju,Prasanna Devaraju/India/IBM,7B,7.5,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,6-8,Development,NaN,NaN,NaN,Banglore
296,B04358,WP2017_017,03415E,Praveen,Haarkara,Praveen K Haarkara/India/IBM,7B,7.5,Active,NaN,...,Business Analyst,Application Architect-Business Intelligence,Premium,NaN,>12,Design,NaN,NaN,NaN,UK
301,B04358,T&M,03592Q,Priyanka,Garodia,Priyanka Garodia/India/IBM,7B,7.5,Active,NaN,...,Teradata,Information Architect-Business Intelligence,Premium,NaN,8-10,Design,NaN,NaN,NaN,Pune
303,B04358,T&M,0028D5,PRIYANKA,ROY,Priyanka Roy6/India/IBM,7B,7.5,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,Architect,10-12,Design,NaN,NaN,NaN,Pune
325,B04363,WP2017_014,05418B,Ravindra,Baviskar,Ravindra G Baviskar/India/IBM,7B,7.5,Active,NaN,...,Java,Application Architect-Cloud.Custom Development,Standard,NaN,8-10,Design,NaN,NaN,NaN,Pune
408,B04358,T&M,117348,Shardendu,Chaudhary,Shardendu K Chaudhary/India/IBM,8,8.0,Active,NaN,...,Project Manager,NaN,NaN,NaN,NaN,design,NaN,NaN,NaN,Pune
416,B04358,T&M,555017,Shrirang,Bhave,Shrirang M Bhave/India/IBM,7B,7.5,Active,NaN,...,Data Modeling,Data Specialist-Data Modeling,Premium,NaN,10-12,Design,NaN,NaN,NaN,Pune
425,B04358,T&M,00875M,Sivakumar,Nair,Sivakumar Nair/India/IBM,8,8.0,Active,NaN,...,Data Modeling,Data Specialist-Data Modeling,Premium,NaN,10-12,Design,NaN,NaN,NaN,Pune
438,B04358,WP2017_030,01245X,Sneha,Kiran,Sneha Kiran/India/IBM,7B,7.5,Active,NaN,...,UX Designer,Application Consultant-Experience Design,Premium,Architect,>12,Design,NaN,NaN,NaN,Bangalore
450,B04363,T&M,04818V,Srihari,Gonela,Srihari Gonela/India/IBM,7B,7.5,Active,NaN,...,Big Data - Spark,Application Developer-Big Data BigInsights,Premium,NaN,6-8,Design,NaN,NaN,NaN,Hyderabad
456,B04363,Lineage,05320F,Subhamoy,Guha,Subhamoy K Guha/India/IBM,9,9.0,Active,NaN,...,Architect,Application Architect-Business Intelligence,Premium,NaN,>12,Design,NaN,NaN,NaN,Pune
508,B04358,T&M,00357N,VENKATA,P,Venkata P Krishnan/India/IBM,7B,7.5,Active,NaN,...,Big Data - Hadoop,Application Architect-Big Data,Premium,Senior Developer,10-12,Core Dev,NaN,NaN,NaN,Hyderabad
517,B04358,T&M,06878L,VINAYAK,KALE,Vinayak Kale/India/IBM,7B,7.5,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,Senior Developer,10-12,Core Dev,NaN,NaN,NaN,Pune
521,B04358,WP2017_030,00579H,Vishal,Jaldawar,Vishal Jaldawar/India/IBM,7B,7.5,Active,NaN,...,Java,Application Developer-Java.EJB,Standard,Architect,8-10,Design,NaN,NaN,NaN,Pune
528,B04358,T&M,01144U,ZISHAN,SYED,Zishan Syed/India/IBM,7B,7.5,Active,NaN,...,Teradata,Project Manager-Complex Programs.BAS,Standard,NaN,6-8,Development,NaN,NaN,NaN,Pune

In [23]:
#3. List potential Ab Initio Leads (7A)
df[(df.Band=='7A') & (df['Status'] == 'Active')  & (df['Skills'] == 'ETL Ab Initio')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
11,B04358,T&M,0052B9,AARTI,KATYARMAL,Aarti Katyarmal/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,NaN,Pune
21,B04358,WP2017_004,04192Z,Abinash,Parida,Abinash Parida/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.AB INITIO,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Banglore
61,B04358,T&M,03141R,Anuprita,Kulkarni,Anuprita R Kulkarni02/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,Architect,6-8,Core Dev,NaN,NaN,NaN,Pune
64,B04363,Lineage,09702C,Anuya,Singhai,Anuya Singhai/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,8-10,Design,NaN,NaN,NaN,Bangalore
206,B04363,Lineage,0314B2,Jyoti,Katiyar,Jyoti Katiyar1/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Bangalore
217,B04358,T&M,00070U,Khyati,Kulkarni,Khyati J Kulkarni/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Pune
229,B04358,T&M,03391U,Madana,Krishnan,Madanagopala Rkrishnan/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,NaN,Bangalore
246,B04358,T&M,0093F9,Milind,Ganure,Milind Ganure/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Application Architect-Business Intelligence,Premium,NaN,6-8,Core Dev,NaN,Will be replaced in the next couple of weeks b...,NaN,Pune
292,B04363,Lineage,04744N,Prashant,Garg,Prashant Garg12/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Architect,4-6,Core Dev,NaN,NaN,NaN,Pune
305,B04358,T&M,0053M9,Priyendu,Pant,Priyendu Pant/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Pune
311,B04358,T&M,04293U,Pushkar,Tiwari,Pushkar Tiwari/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
312,B04358,T&M,03063X,Radhika,Seetharaman,Radhika Seetharaman-1/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,NaN,Bangalore
319,B04358,WP2017_004,04994Z,Ranjit,Sadigale,Ranjit B Sadigale/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,Developer,2-4,Development,NaN,NaN,NaN,Pune
321,B04363,Lineage,03063Y,Raunak,Kothiyal,Raunak Kothiyal/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,6-8,Core Dev,NaN,NaN,NaN,Bangalore
324,B04358,WP2017_004,000753,Ravi,Puramshetty,Ravi Puramshetti/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,8-10,Core Dev,NaN,NaN,NaN,Hyderabad
393,B04358,T&M,0504F6,Sandhya,Namdeo,Sandhya Namdeo,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,2-4,Core Dev,NaN,Consolidation,NaN,Pune
406,B04358,T&M,02680M,Shalini,Laishram,Shalini Laishram/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,NaN,Bangalore
414,B04363,Lineage,0072A0,Shridhar,Maltumkar,Shridhar V Maltumkar/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,NaN,8-10,Design,NaN,NaN,NaN,Pune
423,B04358,WP2017_004,04263T,Sinduja,K,Sinduja K23/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,Senior Developer,6-8,Core Dev,NaN,NaN,NaN,Bangalore
439,B04358,T&M,02918X,Sneha,Swaroop,Sneha Swaroop/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Management Support Specialist-ETL.Ab Initio,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Bangalore
479,B04358,T&M,05032X,Tapas,Sahoo,Tapas R Sahoo/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Pune
531,B04363,Lineage,02509Z,Dileep,Dominic,Dileep R Dominic/India/IBM,7A,7.0,Active,NaN,...,ETL Ab Initio,Data Specialist-ETL.Ab Initio,Premium,NaN,NaN,Core Dev,NaN,NaN,NaN,Pune

In [24]:
#4. List potential other Leads (7A)
df[(df.Band=='7A') & (df['Status'] == 'Active')  & (df['Skills'] != 'ETL Ab Initio')]

,Contract,WP_#,Emp_Code,First_Name,Last_Name,Emp_Notes_ID,Band,Band_Wt,Status,Demand_Confidence,...,Skills,JRSS,Premium,PSL_Role,Years_of_Experience,Role_Category,BCP Critical,Comments,Inactive_Reason,City
18,B04358,T&M,00763Y,Abhishek,Dangre,Abhishek Dangre/India/IBM,7A,7.0,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,Architect,8-10,Core Dev,NaN,NaN,NaN,Pune
20,B04358,T&M,06860A,Abhishek,Swami,Abhishek Swami1/India/IBM,7A,7.0,Active,NaN,...,Cobol,Application Developer-COBOL,Standard,NaN,10-12,Core Dev,NaN,NaN,NaN,Pune
23,B04358,T&M,02126Y,Aditya,Shah,Aditya Shah334/India/IBM,7A,7.0,Active,NaN,...,Change & Release Management,Change & Release Management,NaN,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
25,B04358,WP2017_017,00072I,Aishwarya,Das,Aishwarya Das/India/IBM,7A,7.0,Active,NaN,...,Big Data - Spark,Application Developer-Big Data BigInsights,Premium,NaN,6-8,Design,NaN,NaN,NaN,UK
45,B04358,T&M,05927G,Amol,Patil,Amol Patil/India/IBM,7A,7.0,Active,NaN,...,Program Manager,Technical Team Leader-Middleware,Standard,NaN,8-10,Design,NaN,NaN,NaN,Pune
51,B04363,Lineage,03599Y,Anil,Bhaskara,Anil K Bhaskara/India/IBM,7A,7.0,Active,NaN,...,SAS,Data Specialist-Data Governance,Premium,NaN,6-8,Core Dev,NaN,NaN,NaN,Bangalore
52,B04363,Lineage,AVLV66,Anjali,Garg,Anjali G 66/India/Contr/IBM,7A,7.0,Active,NaN,...,.NET,Application Developer-C#.NET,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
53,B04358,T&M,08416G,Ankit,Bhadauria,Ankit Bhadauria1/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Application Developer-Big Data Tools,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Pune
56,B04358,T&M,09037V,Ankit,Jain,Ankit Jain003/India/IBM,7A,7.0,Active,NaN,...,Business Analyst,Industry Consultant-INDUSTRY.Banking,Premium,Senior Business analyst,8-10,Design,NaN,NaN,NaN,Pune
60,B04363,Lineage,06065D,Anup,Gavate,Anup L Gavate/India/IBM,7A,7.0,Active,NaN,...,.NET,Application Developer-C#.NET,Standard,NaN,2-4,Development,NaN,NaN,NaN,Pune
111,B04358,T&M,0120A6,BISWAJIT,OJHA,Biswajit Ojha1/India/IBM,7A,7.0,Active,NaN,...,ETL Informatica,Data Management Support Specialist-ETL.Informa...,Premium,Senior Developer,10-12,Core Dev,NaN,NaN,NaN,Pune
116,B04358,T&M,04900N,Chandrasekhar,Pekala,Chandrasekhar Pekala/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Development,NaN,NaN,NaN,Hyderabad
142,B04358,T&M,00419S,DEEPAK,VISHWAKARMA,Deepak K Vishwakarma/India/IBM,7A,7.0,Active,NaN,...,ETL Informatica,Data Management Support Specialist-ETL.Informa...,Premium,Architect,6-8,Design,NaN,NaN,NaN,Pune
144,B04363,Lineage,0120A3,Dheeraj,Bang,Dheeraj S Bang1/India/IBM,7A,7.0,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,8-10,Design,NaN,NaN,NaN,Pune
150,B04363,WP2017_014,0319A9,Diptiman,Yarte,Diptiman B Yarte/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,4-6,Development,NaN,NaN,NaN,Pune
153,B04358,T&M,0117C9,ERIC DA,SILVA,Eric Da Silva/India/IBM,7A,7.0,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,Architect,8-10,Core Dev,NaN,NaN,NaN,Pune
174,B04363,WP2017_015,02671T,Gaurav,Neekhra,Gaurav Neekhra02/India/IBM,7A,7.0,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
183,B04363,Lineage,0381F7,Gnaneshwar,Neela,Gnaneshwar Neela/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,Senior Tester,10-12,Core dev,NaN,NaN,NaN,Pune
207,B04358,WP2017_030,01975S,Jyoti,Dwivedi,Jyoti P Dwivedi/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
215,B04358,WP2017_017,00997O,Khileshwar,Prasad,Khileshwar Prasad/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Java.Spring,Standard,NaN,8-10,Core Dev,NaN,NaN,NaN,Pune
218,B04358,WP2017_016,0432C8,Kiran,B,Kiran B13/India/IBM,7A,7.0,Active,NaN,...,BI Reporting - Qlikview,Application Developer-BI Reporting Tools,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Bangalore
222,B04358,T&M,00241S,KRISHNENDU,GUHA,Krishnendu Guha/India/IBM,7A,7.0,Active,NaN,...,ETL Informatica,Data Management Support Specialist-ETL.Informa...,Premium,Architect,6-8,Design,NaN,NaN,Uplifted role category,Pune
231,B04358,T&M,04755W,Madhusmita,Das,Madhusmita Das/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
236,B04358,T&M,0222E9,Mallikarjun Reddy,Katipally,Mallikarjun R katipally/India/IBM,7A,7.0,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Hyderabad
237,B04358,T&M,AVKGMW,MALLIKARJUNA RAO,THOTA,Mallikarjuna Rao Thota 38/India/Contr/IBM,7A,7.0,Active,NaN,...,Change & Release Management,Data Specialist-ETL.Informatica,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
239,B04358,T&M,01919V,Mangesh,Chakurkar,Mangesh Chakurkar/India/IBM,7A,7.0,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
251,B04358,T&M,0060C8,Mudita,Tiwari,Mudita Tiwari/India/IBM,7A,7.0,Active,NaN,...,ETL Informatica,Data Management Support Specialist-ETL.Informa...,Premium,Senior Developer,8-10,Core Dev,NaN,NaN,NaN,Pune
263,B04358,T&M,02355W,Nikhil,Durge,Nikhil Durge/India/IBM,7A,7.0,Active,NaN,...,Teradata,Application Developer-Teradata,Premium,NaN,2-4,Development,NaN,NaN,NaN,Bangalore
294,B04358,T&M,0504G5,Cherka,Prathyusha,Prathyusha Cherka/India/IBM,7A,7.0,Active,NaN,...,Change & Release Management,Change & Release Management,NaN,NaN,2-4,Core Dev,NaN,Consolidation,NaN,Pune
315,B04358,T&M,04759W,Rahul,Chenna,Rahul Chenna/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
320,B04363,WP2017_002,0131C2,Rashmi,Padale,Rashmi S Padale/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,8-10,Core Dev,NaN,NaN,NaN,Pune
382,B04358,WP2017_017,023929,Rituparna,Choudhury,Rituparna Choudhury/India/IBM,7A,7.0,Active,NaN,...,Business Analyst,Business Analyst-Technical Requirements,Standard,NaN,10-12,Core Dev,NaN,NaN,NaN,Pune
392,B04358,T&M,539027,Sandeep,Kumar,Sandeep Kumar5/India/IBM,7A,7.0,Active,NaN,...,Project Manager,Data Management Support Specialist-ETL.Informa...,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
396,B04358,T&M,0204B2,Santosh,Kumar,Santosh Kumar98/India/IBM,7A,7.0,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
398,B04358,WP2017_030,05481E,Sapna,Rajput,Sapna Rajput/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Test Specialist-Custom Applications,Standard,NaN,10-12,Core Dev,NaN,NaN,NaN,Pune
399,B04358,T&M,346458,Satish,Banka,Satish B Banka/India/IBM,7A,7.0,Active,NaN,...,Program Manager,Project Manager-Complex Programs.BAS,Standard,Program Manager,>12,Design,NaN,NaN,NaN,Pune
411,B04358,T&M,07769G,Shirisha,Lakireddy,Shirisha Lakireddy/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Java.Spring,Standard,Senior Developer,8-10,Core Dev,NaN,NaN,NaN,Hyderabad
418,B04358,T&M,AVLDYJ,Shruthi,Ramachandra,Shruthi Ramachandra11/India/Contr/IBM,7A,7.0,Active,NaN,...,Change & Release Management,Data Specialist-ETL.Informatica,Premium,NaN,4-6,Core Dev,NaN,NaN,NaN,Hyderabad
421,B04358,T&M,05030G,Siddharth,Arekar,Siddharth D Arekar/India/IBM,7A,7.0,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,Senior Developer,>12,Development,NaN,NaN,NaN,Pune
437,B04363,Lineage,02562V,Smruti,Mallick,Smruti Mallick1/India/IBM,7A,7.0,Active,NaN,...,Architect,Information Architect-Business Intelligence,Premium,NaN,10-12,Core Dev,NaN,NaN,NaN,Bangalore
448,B04358,T&M,AVK1MF,SREENUBABU,DASARI,Sreenubabu Dasari15/India/Contr/IBM,7A,7.0,Active,NaN,...,Big Data - Hadoop,Application Developer-BIG DATA BIGINSIGHTS,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Hyderabad
454,B04363,NaN,25171,Srinivasa,Vomaravilli,Srinivasa R Vomaravilli/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Test Specialist-Test Consulting,Standard,Architect,8-10,Core Dev,NaN,Assigned on MultiBureau till 7th July with buf...,NaN,Hyderabad
457,B04358,WP2017_004,357133,Subhashini,Rangaswamy,Subhashini Rangaswamy/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,4-6,Development,NaN,NaN,NaN,Bangalore
460,B04358,T&M,0504G4,Sudipta,Roy,Sudipta Roy901/India/IBM,7A,7.0,Active,NaN,...,ETL Informatica,Data Specialist-ETL.Informatica,Premium,NaN,2-4,Development,NaN,Consolidation,NaN,Pune
464,B04358,T&M,AVKGL8,SUMALATHA,KONGA,Sumalatha Konga5/India/Contr/IBM,7A,7.0,Active,NaN,...,Change & Release Management,Data Specialist-ETL.Informatica,Premium,Senior Developer,8-10,Core Dev,NaN,NaN,NaN,Bangalore
466,B04358,T&M,02679S,SUMIT,SHEGOKAR,Sumit Shegokar/India/IBM,7A,7.0,Active,NaN,...,ETL Informatica,Data Management Support Specialist-ETL.Informa...,Premium,Architect,8-10,Core Dev,NaN,NaN,NaN,Pune
467,B04363,WP2017_002,00566Z,Sunil,Dangayach,Sunil Dangayach/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Cloud.Java,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
481,B04358,WP2017_030,0427D4,Vijay,Pandit,Vijay Pandit/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Java.Spring,Standard,NaN,6-8,NaN,NaN,NaN,NaN,Pune
498,B04358,WP2017_030,0129F9,Udit,Asati,Udit Asati011/India/IBM,7A,7.0,Active,NaN,...,Java,Business Analyst-Technical Requirements,Standard,NaN,6-8,Core Dev,NaN,NaN,NaN,Pune
501,B04358,WP2017_028,084145,Ujjaval K,Chowdhari,Ujjaval K Choudhri/India/IBM,7A,7.0,Active,NaN,...,BI Reporting - Cognos,Application Developer-COGNOS.BI,Standard,NaN,4-6,Core Dev,NaN,Consolidation,NaN,Pune
507,B04358,T&M,07550A,Vasanth,Ladda,Vasanth Ladda/India/IBM,7A,7.0,Active,NaN,...,ETL Testing,Test Specialist-Data,Standard,NaN,10-12,Core Dev,NaN,NaN,NaN,Hyderabad
511,B04363,WP2017_015,01813X,VIJAYKUMAR,WADIKAR,Vijaykumar B Wadikar/India/IBM,7A,7.0,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,Senior Developer,4-6,Core Dev,NaN,NaN,NaN,Pune
513,B04358,WP2017_017,0360A2,Vikram,Suthar,Vikram Suthar/India/IBM,7A,7.0,Active,NaN,...,Java,Application Developer-Experience Engineering.F...,Standard,NaN,4-6,Development,NaN,NaN,NaN,Pune
525,B04358,T&M,04078I,VIVEK,GHORPADE,Vivek G Ghorpade/India/IBM,7A,7.0,Active,NaN,...,Big Data - Hadoop,Application Developer-Big Data BigInsights,Premium,Architect,10-12,Core Dev,NaN,NaN,NaN,Pune

In [25]:
#5. What is the Premium % (Active and with Forecast)
#Create a pandas.core.groupby.DataFrameGroupBy object based on the Grouping required
#The following provides a grouping on (["Status","Premium"]) columns
#We can further filter the return columns in the same statement by adding [["Emp_Notes_ID","Band"]]
#gb = df.groupby(["Status","Premium"])[["Emp_Notes_ID","Band_Wt"]]

#But we will break this up into multiple steps for easy calculations
gb = df.groupby(["Status","Premium"])
Active_Premium = gb.get_group(('Active','Premium'))["Emp_Notes_ID"].count()
Active_PremiumPlus = 0 #gb.get_group(('Active','Premium Plus'))["Emp_Notes_ID"].count()
Active_Standard = gb.get_group(('Active','Standard'))["Emp_Notes_ID"].count()
Forecast_Premium = gb.get_group(('Forecast','Premium'))["Emp_Notes_ID"].count()
Forecast_Standard = gb.get_group(('Forecast','Standard'))["Emp_Notes_ID"].count()

Active_Premium_Pct = (Active_Premium + Active_PremiumPlus)*100 / (Active_Premium + Active_PremiumPlus + Active_Standard)
Active_plus_Forecast_Premium_Pct = (Active_Premium + Active_PremiumPlus + Forecast_Premium)*100 / (Active_Premium + Active_PremiumPlus + Active_Standard + Forecast_Premium + Forecast_Standard)

Active_Premium_Pct, Active_plus_Forecast_Premium_Pct

(68.951612903225808, 65.342163355408388)

In [26]:
#6. What is the Band mix (Active and with Forecast)
gb = df.groupby(["Status"])
Active_Band_Wt = gb.get_group(('Active'))['Band_Wt'].mean()
Forecast_Band_Wt = gb.get_group(('Forecast')).Band_Wt.mean()
Active_plus_Forecast_Band_Wt = (gb.get_group(('Active')).Band_Wt.sum() + gb.get_group(('Forecast')).Band_Wt.sum()) / (gb.get_group(('Active')).Band_Wt.count() + gb.get_group(('Forecast')).Band_Wt.count())
Active_Band_Wt, Active_plus_Forecast_Band_Wt

(6.8803921568627455, 6.8443496801705761)

In [27]:
#7. What is the skills distribution?
df.groupby(["Status","Scoped_vs_Non_Scoped","Skills"])['Emp_Notes_ID'].count()

Status    Scoped_vs_Non_Scoped  Skills
Active    Non-scoped            Architect                           6
                                BA                                  3
                                Big Data - Hadoop                  10
                                Big Data - Spark                    1
                                Business Analyst                    5
                                Change & Release Management        14
                                Cobol                               2
                                Data Modeling                       3
                                ETL Ab Initio                      46
                                ETL Informatica                    12
                                ETL Testing                        13
                                Java                                3
                                Program Manager                     2
                                Project Manager                     2
                                Teradata                           18
          Scoped                .NET                                2
                                Architect                           4
                                BI Reporting - Actuate              1
                                BI Reporting - Business Objects     1
                                BI Reporting - Cognos               5
                                BI Reporting - Qlikview             1
                                Big Data - Hadoop                   3
                                Big Data - Spark                    3
                                Business Analyst                    5
                                Cobol                               1
                                ETL Ab Initio                      49
                                ETL Informatica                     2
                                ETL Testing                        13
                                Java                               18
                                Mainframe                           1
                                                                   ..
Forecast  Scoped                .NET                                3
                                BI Reporting - Qlikview             1
                                Data Modeling                       3
                                ETL Ab Initio                      33
                                ETL Testing                         3
                                Java                                1
                                Project Manager                     3
                                Teradata                            4
Inactive  Non-scoped            Architect                           1
                                Big Data - Hadoop                   1
                                Big Data - Spark                    2
                                Big Data Tools                      1
                                Business Analyst                    3
                                Business analyst                    1
                                Change & Release Management         2
                                Data Modeling                       3
                                ETL Ab Initio                      13
                                ETL Informatica                     2
                                ETL Testing                         2
                                Java                                3
                                Program Manager                     1
                                Project Manager                     3
                                Teradata                            5
          Scoped                BI Reporting - Actuate              2
                                Big Data - Spark                    1
                                Business Analyst                    1
                                ETL Ab Initio                       6
                                ETL Testing                         5
                                Java                                7
                                Project Manager                     1
Name: Emp_Notes_ID, dtype: int64

In [28]:
#Revenue Calculations
thisYr = 2017
first_date = pd.Series({1:date(thisYr,1,1), 2:date(thisYr,2,1), 3:date(thisYr,3,1), 4:date(thisYr,4,1), 5:date(thisYr,5,1), 6:date(thisYr,6,1), 7:date(thisYr,7,1), 8:date(thisYr,8,1), 9:date(thisYr,9,1), 10:date(thisYr,10,1), 11:date(thisYr,11,1), 12:date(thisYr,12,1)})
last_date = pd.Series({1:date(thisYr,1,31), 2:date(thisYr,2,28), 3:date(thisYr,3,31), 4:date(thisYr,4,30), 5:date(thisYr,5,31), 6:date(thisYr,6,30), 7:date(thisYr,7,31), 8:date(thisYr,8,31), 9:date(thisYr,9,30), 10:date(thisYr,10,31), 11:date(thisYr,11,30), 12:date(thisYr,12,31)})
local_billing_rate = {1:990, 2:990, 3:990, 4:990, 5:990, 6:990, 7:990, 8:990, 9:990, 10:990, 11:990, 12:990}
landed_billing_rate = {1:455, 2:455, 3:455, 4:455, 5:455, 6:455, 7:455, 8:455, 9:455, 10:455, 11:455, 12:455}
offshore_billing_rate = {1:121, 2:121, 3:121, 4:121, 5:121, 6:121, 7:121, 8:121, 9:121, 10:121, 11:121, 12:121}
billingRate = {"Local":local_billing_rate, "Landed":landed_billing_rate, "Offshore":offshore_billing_rate}
assumed_ute = 0.9

def getDaysForMonth(startDate, endDate, forMonth):

    if startDate == date.min:
        return 0
    elif startDate > last_date[forMonth]:
        return 0
    elif startDate < first_date[forMonth]:
        startDate = first_date[forMonth]
    
    if endDate == date.max:
        endDate = last_date[forMonth]
    elif endDate < first_date[forMonth]:
        return 0
    elif endDate > last_date[forMonth]:
        endDate = last_date[forMonth]    
    
    delta = np.busday_count(startDate, endDate)
    return delta * assumed_ute

def getRevenue (startDate, endDate, locationCategory):
    revenueByMonth = {}
    for month in range(1,13):
        revenueByMonth[month] = getDaysForMonth(startDate, endDate, month) * billingRate[locationCategory][month]
    return revenueByMonth

df2 = pd.DataFrame()
for index, row in df.iterrows():
    nceStart = row['NCE_Start_Date']
    nceEnd = row['NCE_End_Date']
    transitionStart = row['Transition_Start_Date']
    transitionEnd = row['Transition_End_Date']
    billingStart = row['Billing_Start_Date']
    billingEnd = row['Billing_End_Date']
    locationCategory = row['Location_Category']
    
    if pd.isnull(billingEnd): #Very important technique of finding null -- pd.isnull(xxx)
        billingEnd = datetime(thisYr,12,31,0,0,0)
        
    revSer = getRevenue(billingStart.date(), billingEnd.date(),locationCategory)
    df2 = df2.append([revSer],index) #Just a df2.append([..]) does not work. Has to be df2 = df2...

df3 = df.join(df2)
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('/Users/surjitdas/Box Sync/Barclays Data Tower/Governance/Operations/calculations.xlsx', engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object.
df3.to_excel(writer, sheet_name='Revenue')

# Close the Pandas Excel writer and output the Excel file.
writer.save()
print("Done")

ValueError: cannot convert float NaN to integer

In [ ]:
df[(df['Status'] == 'Forecast')  & (df.Confidence=='Identified') ]